"""schema initial du diagramme de classes

Revision ID: 62bfee3b99c0
Revises: 
Create Date: 2026-09-25 20:53:43.146417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bfee3b99c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noeuds_hopital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_salle', sa.String(), nullable=False),
    sa.Column('etage', sa.Integer(), nullable=False),
    sa.Column('type_noeud', sa.Enum('SERVICE', 'COULOIR', 'ASCENSEUR', 'DEPOT_MATERIEL', name='type_noeud'), nullable=False),
    sa.Column('uid_tag_nfc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid_tag_nfc')
    )
    op.create_index(op.f('ix_noeuds_hopital_id'), 'noeuds_hopital', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_hospitalisation', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('code_bracelet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_code_bracelet'), 'patients', ['code_bracelet'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_id_hospitalisation'), 'patients', ['id_hospitalisation'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('REGULATEUR', 'MEDECIN', 'BRANCARDIER', 'ADMIN', name='role'), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_nom_utilisateur'), 'utilisateurs', ['nom_utilisateur'], unique=True)
    op.create_table('aretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noeud_a_id', sa.Integer(), nullable=False),
    sa.Column('noeud_b_id', sa.Integer(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('est_bloque', sa.Boolean(), nullable=False),
    sa.CheckConstraint('noeud_a_id <> noeud_b_id', name='ck_arete_noeuds_distincts'),
    sa.CheckConstraint('poids > 0', name='ck_arete_poids_positif'),
    sa.ForeignKeyConstraint(['noeud_a_id'], ['noeuds_hopital.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['noeud_b_id'], ['noeuds_hopital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('noeud_a_id', 'noeud_b_id', name='uq_arete_noeuds')
    )
    op.create_index(op.f('ix_aretes_id'), 'aretes', ['id'], unique=False)
    op.create_table('brancardiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('DISPONIBLE', 'EN_MISSION', 'EN_PAUSE', 'INDISPONIBLE', name='statut_agent'), nullable=False),
    sa.Column('compteur_mission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journaux_assistance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emetteur_id', sa.Integer(), nullable=False),
    sa.Column('chemin_audio', sa.String(), nullable=False),
    sa.Column('texte_transcrit', sa.Text(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=True),
    sa.Column('entites_extraites', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['emetteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journaux_assistance_emetteur_id'), 'journaux_assistance', ['emetteur_id'], unique=False)
    op.create_index(op.f('ix_journaux_assistance_id'), 'journaux_assistance', ['id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brancardier_id', sa.Integer(), nullable=False),
    sa.Column('noeud_id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brancardier_id'], ['brancardiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['noeud_id'], ['noeuds_hopital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_brancardier_id'), 'detections', ['brancardier_id'], unique=False)
    op.create_index(op.f('ix_detections_date_heure'), 'detections', ['date_heure'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau_urgence', sa.Enum('BASSE', 'MOYENNE', 'HAUTE', 'URGENT', name='niveau_urgence'), nullable=False),
    sa.Column('materiel_requis', sa.Enum('RIEN', 'CHAISE_ROULANTE', 'LIT_MEDICAL', 'OXYGENE', name='materiel'), nullable=False),
    sa.Column('materiel_deja_dispo', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PROPOSE', 'EN_TRANSIT', 'TERMINE', 'ANNULE', name='statut_mission'), nullable=False),
    sa.Column('itineraire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescripteur_id', sa.Integer(), nullable=False),
    sa.Column('brancardier_id', sa.Integer(), nullable=True),
    sa.Column('noeud_source_id', sa.Integer(), nullable=False),
    sa.Column('noeud_destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brancardier_id'], ['brancardiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['noeud_destination_id'], ['noeuds_hopital.id'], ),
    sa.ForeignKeyConstraint(['noeud_source_id'], ['noeuds_hopital.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescripteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_brancardier_id'), 'missions', ['brancardier_id'], unique=False)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_statut'), 'missions', ['statut'], unique=False)
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('statut_modifie_en', sa.Enum('EN_ATTENTE', 'PROPOSE', 'EN_TRANSIT', 'TERMINE', 'ANNULE', name='statut_mission'), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methode_verification', sa.Enum('MANUEL', 'SCAN_CODE_QR', 'BADGE_NFC', 'COMMANDE_VOCALE', 'FORCE_URGENCE', name='methode_verification'), nullable=False),
    sa.Column('motif_refus', sa.Enum('MATERIEL_DEFECTUEUX', 'INDISPONIBILITE_PHYSIQUE', 'URGENCE_PRIORITAIRE', 'FIN_SERVICE', name='motif_refus'), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiques_id'), 'historiques', ['id'], unique=False)
    op.create_index(op.f('ix_historiques_mission_id'), 'historiques', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historiques_mission_id'), table_name='historiques')
    op.drop_index(op.f('ix_historiques_id'), table_name='historiques')
    op.drop_table('historiques')
    op.drop_index(op.f('ix_missions_statut'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_brancardier_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_date_heure'), table_name='detections')
    op.drop_index(op.f('ix_detections_brancardier_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_journaux_assistance_id'), table_name='journaux_assistance')
    op.drop_index(op.f('ix_journaux_assistance_emetteur_id'), table_name='journaux_assistance')
    op.drop_table('journaux_assistance')
    op.drop_table('brancardiers')
    op.drop_index(op.f('ix_aretes_id'), table_name='aretes')
    op.drop_table('aretes')
    op.drop_index(op.f('ix_utilisateurs_nom_utilisateur'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_patients_id_hospitalisation'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_code_bracelet'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_noeuds_hopital_id'), table_name='noeuds_hopital')
    op.drop_table('noeuds_hopital')
    # ### end Alembic commands ###

    # Les types ENUM de PostgreSQL ne sont pas supprimés avec les tables
    for nom in ("materiel", "methode_verification", "motif_refus", "niveau_urgence",
                "role", "statut_agent", "statut_mission", "type_noeud"):
        op.execute(f"DROP TYPE IF EXISTS {nom}")
