"""duree estimee mission

Revision ID: a7fe1aedb861
Revises: b1a82a133f64
Create Date: 2026-10-01 12:09:06.295498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fe1aedb861'
down_revision: Union[str, Sequence[str], None] = 'b1a82a133f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('duree_estimee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'duree_estimee')
    # ### end Alembic commands ###
