"""admission patient identite

Revision ID: bf7a49c18961
Revises: a3c9e1f47b20
Create Date: 2026-09-27 15:24:25.356174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7a49c18961'
down_revision: Union[str, Sequence[str], None] = 'a3c9e1f47b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sexe = sa.Enum('MASCULIN', 'FEMININ', 'INDETERMINE', name='sexe')
statut_identite = sa.Enum('PROVISOIRE', 'VALIDEE', name='statut_identite')


def upgrade() -> None:
    """Upgrade schema."""
    # add_column ne crée pas les types ENUM : il faut les créer avant les colonnes
    sexe.create(op.get_bind(), checkfirst=True)
    statut_identite.create(op.get_bind(), checkfirst=True)
    
    # Les patients déjà en base reçoivent les valeurs par défaut (server_default)
    op.add_column('patients', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('sexe', sa.Enum('MASCULIN', 'FEMININ', 'INDETERMINE', name='sexe'), server_default='INDETERMINE', nullable=False))
    op.add_column('patients', sa.Column('statut_identite', sa.Enum('PROVISOIRE', 'VALIDEE', name='statut_identite'), server_default='VALIDEE', nullable=False))
    op.add_column('patients', sa.Column('date_admission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'date_admission')
    op.drop_column('patients', 'statut_identite')
    op.drop_column('patients', 'sexe')
    op.drop_column('patients', 'date_naissance')
    
    # Les types ENUM ne disparaissent pas avec les colonnes
    statut_identite.drop(op.get_bind(), checkfirst=True)
    sexe.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
